project:
  type: website
  output-dir: docs

website:
  title: "inoxb198.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - about.qmd

format:
  html:
    theme: 
      light: quartz
      dark: vapor
    css: styles.css
    toc: true

editor: visual

